language: scala
dist: trusty
sudo: false

scala:
  - 2.11.11

jdk:
  - oraclejdk8

matrix:
  include:
    - scala: 2.12.4
      jdk: oraclejdk8
    - scala: 2.11.11
      jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers
    - $HOME/.coursier

install:
  - pip install --user codecov

script:
  - |
    if [[ "$TRAVIS_SCALA_VERSION" = 2.12.* ]]; then
      sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageOff && codecov
    else
      sbt ++$TRAVIS_SCALA_VERSION clean test
    fi
  - |
    if [[ "$TRAVIS_BRANCH" = "master" && $(cat version.sbt) =~ "-SNAPSHOT" ]]; then
      gpg_key_path=$HOME/.gnupg
      mkdir -p $gpg_key_path
      echo $GPG_KEY | base64 --decode > $gpg_key_path/secring.gpg
      sbt ++$TRAVIS_SCALA_VERSION publishSigned
    fi

before_cache:
  # See http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
